### ISSUE TITLE
санах ойг хэт их ашиглаж байгаа хэсгүүдийг нягталж , хэрэглээг бууруулах

### ISSUE THREAD

**Issue by Naranmandakh** [Naranmandakh/SignLanguageIOS#20]

**Comment by Naranmandakh** [comment]
Цагаан толгой ангилал : 180MB - 300MB хүртэл зарцуулж байна!!!

**Comment by tortuvshin** [comment]
@Naranmandakh зурагнууд чинь хэтэрхий их хэмжээтэй байна уу

**Comment by Naranmandakh** [comment]
тиймээ , зурагнуудаа засахдаа нягралыг нь багасганаа, бас өөс юунаас болоод байна гэдгийг debug хийж үзэх л хэрэгтэй байна. сүүлд нь шалгана.
